# Megatron SFT Trainer Configuration
# This configuration supports MoE models with expert parallelism

data:
  train_batch_size: 256
  micro_batch_size_per_gpu: 4  # this is also val batch size
  train_files: ~/data/gsm8k/train.parquet
  val_files: ~/data/gsm8k/test.parquet
  # Single-turn settings
  prompt_key: question
  response_key: answer
  prompt_dict_keys: null
  response_dict_keys: null
  # Multi-turn settings
  multiturn:
    enable: false  # Set to true to use multi-turn dataset
    messages_key: messages  # Key for messages list in multi-turn mode
    tools_key: tools  # Key for tools list in multi-turn mode
    enable_thinking_key: enable_thinking  # Whether to enable thinking in multi-turn mode
  max_length: 1024
  truncation: error
  balance_dp_token: False
  chat_template: null
  custom_cls:
    path: null
    name: null
  use_shm: False

model:
  partial_pretrain: ~/models/deepseek-ai/DeepSeek-V3-0324  # Path to MoE model
  use_shm: False
  model_dtype: bf16  # bf16, fp16, fp32
  external_lib: null
  enable_gradient_checkpointing: True
  trust_remote_code: False
  load_weight: True
  
  # Model override config for MoE
  override_config:
    model_config: {}
    moe_config:
      freeze_moe_router: False  # Set to True to freeze MoE router during training

# Megatron-specific configuration
megatron:
  # Parallelism configuration
  tensor_model_parallel_size: 1      # TP size
  pipeline_model_parallel_size: 1    # PP size  
  expert_model_parallel_size: 1      # EP size for MoE models
  context_parallel_size: 1           # CP size
  virtual_pipeline_model_parallel_size: null
  sequence_parallel: True
  
  # Distributed optimizer
  use_distributed_optimizer: True
  
  # Checkpointing
  use_dist_checkpointing: False
  dist_checkpointing_path: null
  
  # Offloading strategies
  param_offload: False
  grad_offload: False
  optimizer_offload: False
  
  # Random seed
  seed: 42
  
  # Override configs
  override_ddp_config: {}
  override_transformer_config: {}

# Optimizer configuration
optim:
  lr: 1e-5
  betas: [0.9, 0.95]
  weight_decay: 0.01
  warmup_steps_ratio: 0.1
  clip_grad: 1.0
  lr_scheduler: cosine
  
  # Megatron optimizer specific
  optimizer: adam
  lr_warmup_init: 0.0
  lr_warmup_steps: null
  lr_decay_steps: null
  lr_decay_style: constant
  min_lr: 0.0
  weight_decay_incr_style: constant
  lr_wsd_decay_style: exponential
  lr_wsd_decay_steps: null
  use_checkpoint_opt_param_scheduler: False

# Trainer configuration
trainer:
  default_local_dir: checkpoints/${trainer.project_name}/${trainer.experiment_name}
  default_hdfs_dir: null
  resume_path: null
  project_name: moe-sft
  experiment_name: test
  total_epochs: 4
  total_training_steps: null
  logger: ['console', 'wandb']
  seed: 1
  save_freq: 1000
  test_freq: 100
  nnodes: 1
  n_gpus_per_node: 8
  max_ckpt_to_keep: null